server:
  port: ${GAZER_PORT:6000}
  error:
    whitelabel:
      enabled: false

logging:
  level:
    root: info
    org.codebusters: ${GAZER_LOG_LEVEL:info}

spring:
  datasource:
    # jdbc:postgresql://localhost:5432/dbName
    url: ${GAZER_DATABASE_DATASOURCE_URL}
    username: ${GAZER_DATABASE_USER}
    password: ${GAZER_DATABASE_PASSWORD}
    hikari:
      maximum-pool-size: ${GAZER_DATABASE_POOL_SIZE:5}
      connection-timeout: ${GAZER_DATABASE_CONNECTION_TIMEOUT:5000}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    show-sql: false
  mvc:
    throw-exception-if-no-handler-found: true

gazer:
  spotify:
    client-id: ${GAZER_SPOTIFY_CLIENT_ID}
    client-secret: ${GAZER_SPOTIFY_CLIENT_SECRET}
    base-accounts-url: https://accounts.spotify.com
    base-api-url: https://api.spotify.com/v1
    releases-page-length: 50
  flow:
    run-on-startup: ${GAZER_FLOW_ON_STARTUP:false}
    scheduler-cron: ${GAZER_FLOW_SCHEDULER_CRON:0 0 3 * * *}
  app:
    get-releases:
      max-page-size: ${GAZER_RELEASES_MAX_PAGE_SIZE:20}
      max-genre-length: ${GAZER_RELEASES_MAX_GENRE_SIZE:50}
      max-genres-size: ${GAZER_RELEASES_MAX_GENRES_AMOUNT:30}
      char-whitelist: ${GAZER_RELEASES_CHAR_WHITELIST:}
      char-blacklist: ${GAZER_RELEASES_CHAR_BLACKLIST:}
