server:
  port: ${GAZER_PORT:6000}

logging:
  level:
    root: info
    org.codebusters: ${GAZER_LOG_LEVEL:info}

spring:
  datasource:
    # jdbc:postgresql://localhost:5432/dbName
    url: ${GAZER_DATABASE_DATASOURCE_URL}
    username: ${GAZER_DATABASE_USER}
    password: ${GAZER_DATABASE_PASSWORD}
    hikari:
      maximum-pool-size: ${GAZER_DATABASE_POOL_SIZE:5}
      connection-timeout: ${GAZER_DATABASE_CONNECTION_TIMEOUT:5000}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    show-sql: false

gazer:
  spotify:
    client-id: ${GAZER_SPOTIFY_CLIENT_ID}
    client-secret: ${GAZER_SPOTIFY_CLIENT_SECRET}
    base-accounts-url: https://accounts.spotify.com
    base-api-url: https://api.spotify.com/v1
    releases-page-length: 50
  flow:
    run-on-startup: ${GAZER_FLOW_ON_STARTUP:false}
    scheduler-cron: ${GAZER_FLOW_SCHEDULER_CRON:0 0 3 * * *}

