server:
  port: ${GAZER_PORT:5010}
  tomcat:
    threads:
      max: 200

logging:
  level:
    root: info
    org.codebusters: ${GAZER_LOG_LEVEL:info}

gazer:
  message-generator: ${GAZER_MESSAGE_PORT:hello}
