server:
  port: ${GAZER_PORT:6000}

logging:
  level:
    root: info
    org.codebusters: ${GAZER_LOG_LEVEL:info}

gazer:
  spotify:
    client-id: ${GAZER_SPOTIFY_CLIENT_ID}
    client-secret: ${GAZER_SPOTIFY_CLIENT_SECRET}
    base-accounts-url: https://accounts.spotify.com
    base-api-url: https://api.spotify.com
